<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>MQA-LibInstaller</RootNamespace>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Drawing.Common" Version="10.0.10" />
    <PackageReference Include="System.Resources.Extensions" Version="10.0.10" />
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.4.1" />
    <PackageReference Include="NAudio" Version="2.3.0" />
    <PackageReference Include="NAudio.Asio" Version="2.3.0" />
    <PackageReference Include="NAudio.Core" Version="2.3.0" />
    <PackageReference Include="NAudio.Midi" Version="2.3.0" />
    <PackageReference Include="NAudio.Wasapi" Version="2.3.0" />
    <PackageReference Include="NAudio.WinForms" Version="2.3.0" />
    <PackageReference Include="NAudio.WinMM" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="SharpDX.MediaFoundation" Version="4.2.0" />
    <PackageReference Include="SharpDX.XAudio2" Version="4.2.0" />
    <PackageReference Include="SharpDX.XInput" Version="4.2.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MapleLib">
      <HintPath>./MapleLib.dll</HintPath>
    </Reference>
    <Reference Include="spine-csharp">
      <HintPath>./spine-csharp.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
